spring:
  application:
    name: picpay
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/picpaydb
    username: admin
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

client:
  authorization-service:
    url: https://run.mocky.io/v3/94b33905-b531-44b5-900d-0bbff13cbaa0
  notification-service:
    url: https://run.mocky.io/v3/0a8ce913-1f03-44f1-bfe3-21544c300ed0